### ISSUE TITLE
textos incorrectos en la seccion de comsiones

### ISSUE THREAD

**Issue by strugart** [PartidoDeLaRed/partidodelared.github.io#1]
En:
(Financiamiento)
~~Monsanto, Barrick Gold, IBM, Google~~. NO, nos autofinanciamos como podemos y como queremos para que nadie nos venga a pedir nada después, porque nuestro voto es nuestro.

Debería ser: 
~~Monsanto, Barrick Gold, IBM, Google~~. NO, nos autofinanciamos pensando en crowdfunding, favoreciendo el contacto con otra organizaciones, impulsando la transparencia y a favor de cambios en la ley que hable de un voto y no un secreto.

En
(Arte)
Debería ser:
nodo.Arte (no somos comision, genera confusion ya que hablamos en otros tonos)
Espacio donde se buscan intervenciones de toda indole mientras exploramos ideas sobre las relaciones de lo artistico y lo politico.

**Comment by fvilledary** [comment]
solved with commit [515cada](https://github.com/PartidoDeLaRed/partidodelared.github.io/commit/515cadac4f9a760527e918c8250e21e1251769de)
